# Generated by Django 3.2.4 on 2021-06-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='Alphabets and digits mix', max_length=100, unique=True),
        ),
    ]
